package paradigma0621.cleanchess.model.NEW;

public enum ViewerStateEnum {
    NEXT_MOVE,
    PREVIOUS_MOVE,
    ROTATE_BOARD,
    SHOW_SHORTCUTS_HELP_MESSAGE,
    SHOW_WHO_PLAY_AND_GAME_INFO,
    LOAD_SIMPLE_FEN,
    LOAD_SIMPLE_PGN,
    RESTART_PGN_POSITION,
    ZOOM_IN,
    ZOOM_OUT,
    FULL_SCREEN,
    SHOW_HIDE_LABEL,
    LOAD_PGN_WITH_MANY_GAMES
}
