#!/bin/bash
(
echo "setoption name Hash value 128";
echo "setoption name threads value 1";
echo "setoption name Contempt Factor value 50";
echo "position fen rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 0";
echo "go movetime 1000"
sleep 1
) | /home/lucas/Documentos/xadrez/java/xadrezQueEstaValendo-16.9/cleanchess/src/main/resources/executable/stockfish > /home/lucas/Documentos/xadrez/java/xadrezQueEstaValendo-16.9/cleanchess/src/main/resources/playedGames/out-X3
